### ISSUE TITLE
Intel boost - change method to be a continuous buff

### ISSUE THREAD

**Issue by Ithilis** [FAForever/nomads#105]
This function is fundamentaly wrong. While use of intel is pasive, so have toggle that need be actively clicked when after some time (3s) it will bet more intel, that work as pasive warning is wrong. So it should be rework for pasive toggle that increse intel, but will drain far more energy. 

Proto numbers are like -25% intel and same drain. 
or +15% intel and 50% more drain.  

But concrete values are arbitary, this issue is about rewok funcion.

**Comment by Exotic-Retard** [comment]
looks like we need a balance tag cookienoob xD

**Comment by CookieNoob** [comment]
yea
/me goes making one

**Comment by Ithilis** [comment]
i was think abotu this, and easy way how this should be done is add new nomad buff.  (check how work bombard/anchor buffs  -> lua/nomadsbuff) and when its on then multiplier radar by  1.25  and energy drain by 1.5    and we can remove lot of potencial risky code and simply add this buff into unis.

**Comment by Exotic-Retard** [comment]
fixed in 02875ab0a18f83e523b83fc103e325c00e47585c 7bb275f336d5493d76bf69f60e6320d6cf4be041 f054c6651d2e1c38178f8da83c852f2abeb622b7 and more!
