### ISSUE TITLE
acu explosion disables other acu explosions nearby

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/nomads#128]
probably related to the black hole functionality 

in case of a draw, only the nomads explosion is shown and the other explosion is completely removed (including the damage)

**Comment by JJ173** [comment]
These issues are like working with ithilis 💯

**Comment by JJ173** [comment]
Anyway, enough kidding aside. I tested this in our latest version with a UEF and Nomad ACU. Blowing them both up at the same time caused no issues. I heard and saw the UEF ACU Explosion as well as the Nomads one.

**Comment by Exotic-Retard** [comment]
48c7719d2fcb095fd3427bc83c332214d27fa77c
should fix this, needs testing to confirm

**Comment by Exotic-Retard** [comment]
been long enough and issue seems to be gone, so fix is working. closing :>
