### ISSUE TITLE
nomads causes heavy load on rendering thread

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/nomads#164]
someone reported that the FPS went down to ~15 in a wonder 5v5 game.

I'm not sure if this is related to a change we made (I doubt it) or if that was present in nomads all the time. It needs investigation.

**Comment by speed2CZ** [comment]
Or caused by the map since there are fucked up wonder versions that kill FPS

**Comment by CookieNoob** [comment]
I am watching that replay atm, seems like the fps do indeed drop when zoomed on a medium zoom level. From fully zoomed out, 2 and 3 levels closer, the FPS go down (in that replay) and when zoomed in closer, the FPS go back up to max again.

**Comment by TheKeyBlue** [comment]
Watching a replay of my nomads game, when put on +10 the game started lagging(?) insanely.
This was the case for other players watching it too. 
This could be related?

[5808545-KeyBlue.zip](https://github.com/Nomads-Project/nomads/files/780581/5808545-KeyBlue.zip)

**Comment by CookieNoob** [comment]
yea its probably related, the visual "lag" is caused by the rendering thread not being fast enough... soo what could cause this?

**Comment by Exotic-Retard** [comment]
it could actually be the models - dudekaherdon mentioned that the acu model has like 10x the poly count it should, and that theyre all horribly optimized, with disconnected edges everywhere and stuff

**Comment by Exotic-Retard** [comment]
another great way to cause lag is to have a lot of range circles on units. its actually the n1 fps dropper.

interestingly designing more specialized units with fewer range circles will help with fps a lot xD

**Comment by CookieNoob** [comment]
we should really try to figure this out. The lag appears already after a few seconds in a replay (on +10), it cant be connected to the range circles. At that point there are not even units on the field (except for an acu and a factory maybe) thus models are not really a possible cause.

**Comment by Exotic-Retard** [comment]
found the cause of the lag, its the build beams.
to test: spawn 50 t1 engineers, set them to all reclaim trees. set 5 engineers to build a line of pgens. set game speed to +10 and turn on the fps counter. mine dropped from 60 to 20 or less when the engineers were just building.

working on a fix now :>

**Comment by Exotic-Retard** [comment]
https://github.com/FAForever/nomads/commit/d1a19273da15fe8df643f03cca0032227b779e24 attempted fix here, hopefully that puts the issue to rest. will wait a bit to confirm its fixed first.

**Comment by Exotic-Retard** [comment]
Alright so, havent seen any lag since then, so assuming this issue is fixed. If something else comes up we can open a new one. :>
