### ISSUE TITLE
create new model for nova amphibious tank

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/nomads#259]
the nova tank got changed from hover to amphibious, but it still looks like a hover tank. Add a new model that also uses tracks.

Furthermore, the current nova shoots the ground (with the rocket launchers) on any map with slightly non-flat ground.

**Comment by CookieNoob** [comment]
@Exotic-Retard plz texture and finish the nova model so we can release a new nomads version today. IceDreamer seemed to forgot to notify me about the date when he wanted to release the new patch (3680), as that broke nomads. This issue is fixed in the develop version ofc cause, but I would like to have the new version of the nova in the next update.

**Comment by CookieNoob** [comment]
high, because the current nova shoots the ground (with the rocket launchers) on any map with slightly non-flat ground.

**Comment by JJ173** [comment]
Closed - Part of model improvements.
