### ISSUE TITLE
t2 transports loads only a single t3 unit at the same time when folded

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/nomads#288]
the t2 transport only picks up a single t3 unit when its in the fully folded state. When its unfolded or in the transition to folded, it will pick up two units (as its supposed to)

**Comment by CookieNoob** [comment]
some theory crafting: 
- maybe the attachment bone is pointing in the wrong direction when folded
- both relevant attachment bones are on top of each other when folded

**Comment by JJ173** [comment]
@Exotic-Retard Could this be related to the fix you pushed with the T2 transport?

**Comment by Exotic-Retard** [comment]
oh right yeah, this issue is fixed in https://github.com/FAForever/nomads/commit/65a2b6e34f3a34d99602723b116fb0f658ed4d85

there is still a little scope for the issue to remain if you try super hard to load it immediately after its built. would be fixed entirely by changing the transport model
