### ISSUE TITLE
SACU preset mixed up

### ISSUE THREAD

**Issue by FlyingThunder** [FAForever/nomads#330]
There is a "Preset: Producer" that claims to have RAS and building on both arms - this one in fact ONLY has RAS.

Then there is a preset that has no icon and no description but the name says "Preset: RAS". This one has RAS _and_ both building arms.

**Comment by CookieNoob** [comment]
thats rather easy to fix, I'll do that at the weekend (probably). I cant promise when it will be deployed though (needs more than that to make an update).

**Comment by CookieNoob** [comment]
fixed here: https://github.com/FAForever/nomads/commit/248dadbaa4b9c6db0512a97c10acd051f8a47650
