### ISSUE TITLE
Nuke weapon prevents deathanimation

### ISSUE THREAD

**Issue by Apofenas** [FAForever/nomads#349]
For some reasons nuke may just bug out and prevent death animation for exps so their model doesnt die and stands still for the rest of ethernity

Error from log

warning: Error running OnKilled script in Entity ual0401 at 46f9fe08: ...md\effects\entities\nblackhole\nblackhole_script.lua(127): attempt to call method `CheckVeteranLevel' (a nil value)
         stack traceback:
         	...md\effects\entities\nblackhole\nblackhole_script.lua(127): in function `OnKilledUnit'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(4855): in function `OnKilledByBlackHole'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(4439): in function `OnKilled'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(1484): in function `OnKilled'
         	...\gamedata\units.nx2\units\ual0401\ual0401_script.lua(23): in function <...\gamedata\units.nx2\units\ual0401\ual0401_script.lua:22>
         	[C]: in function `Kill'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1145): in function `DoTakeDamage'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1105): in function <...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua:1097>
         	[C]: in function `DamageArea'
         	...md\effects\entities\nblackhole\nblackhole_script.lua(109): in function <...md\effects\entities\nblackhole\nblackhole_script.lua:106>

**Comment by CookieNoob** [comment]
the reason is simple: the veterancy system got changed. more precisely here: https://github.com/FAForever/fa/commit/cc456c1765cecc6f442cf7961ec3e7e418149b5e

**Comment by Exotic-Retard** [comment]
in part this fix requires https://github.com/FAForever/fa/pull/2678
more commits to follow regarding nuke code after that is released in faf

**Comment by Exotic-Retard** [comment]
48c7719d2fcb095fd3427bc83c332214d27fa77c
should fix this, needs testing to confirm

**Comment by Exotic-Retard** [comment]
been long enough and issue seems to be gone, so fix is working. closing :>
