### ISSUE TITLE
OC is broken

### ISSUE THREAD

**Issue by Apofenas** [FAForever/nomads#350]
Some1 fix?

**Comment by Apofenas** [comment]
Right, on a request to clarify the bug. Somewhere in may-june balance team did OC rework with a lot of hard coded crap. That broke nomad OC so it does old 12k damage and doesn't consume power. 

Sooo, this is not only outdated. It is also bugged now. I have no idea how to..., what to... whatever.

_I know some guy who is familiar with the new OC code would gladly fix it for us for free... but he is being pushed out of this repo. :(_

**Comment by Exotic-Retard** [comment]
https://github.com/FAForever/nomads/commit/0e6148e225f0ddee6dac698882de457925e559ea
yeah so this is functionally fixed, but there is scope for some cosmetic changes, such as making the OC projectile look more different from the regular one, adding new sound effect for it, and other such things.

**Comment by Exotic-Retard** [comment]
and finished in https://github.com/FAForever/nomads/commit/cd9917d54d8c8c8b7a9fb1cebc1d3cc3ba02ddcb :>
