### ISSUE TITLE
Replace T2 gunship ground weapon with missile weapon

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/nomads#420]
Currently the torpedo gunship has torpedoes and a gun. Instead, it should have two special missile weapons - one that shoots missile like the cybran t2 gunship, and another that is used for underwater targets - shooting the same missiles but those can enter underwater and turn into torpedoes.

This gives the illusion that its firing one weapon in both cases but allows the DPS to be changed on it for submarine specific damage.

**Comment by Ithilis** [comment]
https://github.com/FAForever/nomads/compare/T2-Vanguard-gunship

kind of solution.

**Comment by Exotic-Retard** [comment]
2abdfa5338703fcd6d9cf8cf8f14ea3efb1e05ce done here
