### ISSUE TITLE
Warning message on SCU death

### ISSUE THREAD

**Issue by Apofenas** [FAForever/nomads#434]
SCU death creates `WARNING: Nomads: Shields disabled by capacitor ability` comment in log file

**Comment by speed2CZ** [comment]
https://github.com/FAForever/nomads/blob/develop/lua/nomadsutils.lua#L987-L994

It's not exactly causing any issues, Im not sure I want to dig into that. I "could" change it to simple LOG instead... or remote it entirely.

**Comment by Exotic-Retard** [comment]
this will be fixed when the scu is replaced. right now it doesnt do that much actual breaking so we will just wait for it to disappear

**Comment by Exotic-Retard** [comment]
biscuit suggested to make this wontfix and close it since it will close itself eventually, so thats what ill do!
