### ISSUE TITLE
ACU as wrong description of heavy bombardment upgrade

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/nomads#448]
This upgrade has been added recently, and is still missing its description.

The orbital bombardment upgrade is now two upgrades, which should be called:
`Light Orbital Bombardment`
`Heavy Orbital Bombardment`

And have all appropriate strings and localization tags made and synced.

**Comment by StevenC21** [comment]
[PR 449](https://github.com/FAForever/nomads/pull/449) fixes this issue.
