### ISSUE TITLE
Don't burn area after game start - BUG

### ISSUE THREAD

**Issue by Ithilis** [FAForever/nomads#462]
replay n.: #10409289 

After the game start and ACU fall down from the sky I must reclaim area before build, what let me pretty behind. Not sure what is related, and sure that it not happend in every scenario.

**Comment by Exotic-Retard** [comment]
partial fix in 94e17e8579e7e25849da2c506b3845e6f834715b
but needs more work to be 100% reliable. not quite sure whats going on here but its definitely the Nomads meteor projectiles fault (replacing it with the default other factions one fixes stuff)

This might wait until the warp in animation is redone.

**Comment by Exotic-Retard** [comment]
fixed in a10485bbe219a99029c16fcbb05cb57bba19e686
