### ISSUE TITLE
Overcharge have wrong rof

### ISSUE THREAD

**Issue by Ithilis** [FAForever/nomads#463]
ACU have two OC, one for auto oc and second for a manual, both of them have the wrong time. One is 3,3sec and on auto its 4sec. In faf OC have 5 sec reload time. 

This is there from some ancient time where time on OC was different, there should be only one OC in weapon and have reload time same 5 sec.

**Comment by Exotic-Retard** [comment]
fixed in https://github.com/FAForever/nomads/commit/d945b008d061172fb105842bac75505452910ab3
