### ISSUE TITLE
Missing faction covert for AI templates

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/nomads#475]
There used to be this function hooked to add support for nomads campaign AI
https://github.com/FAForever/fa/blob/develop/lua/sim/ScenarioUtilities.lua#L1506-L1549

now its gone and nomads AI wont do shit, who is to blame?

**Comment by Exotic-Retard** [comment]
fixed in 8254d4ab903bde04321018319f9762504b4c4f4d <3
