### ISSUE TITLE
Air staging facility have wrong symbol as T2

### ISSUE THREAD

**Issue by Ithilis** [FAForever/nomads#499]

**Comment by Apofenas** [comment]
Well, that's the case for all factions XD

**Comment by Ithilis** [comment]
No in other faction it actualy show as T1 now, only nomads stay, not sure what is going on :/

**Comment by Apofenas** [comment]
Oh, that was Speed who fixed that for FAF. Okay than, i'll do that tommorow

**Comment by speed2CZ** [comment]
Its already fixed https://github.com/FAForever/nomads/pull/489
Maybe test the most up to date version...

**Comment by Exotic-Retard** [comment]
yeah, already fixed in nomads!
![](https://i.imgur.com/ZUP0dsY.png)
