### ISSUE TITLE
T3 Artillery stops firing

### ISSUE THREAD

**Issue by philipsdirk** [FAForever/nomads#507]
I've had this issue happen in multiple games with and without mods. After I've build the T3 Artillery Desolator. It starts firing like normal but at some point it stops. Last game this happend after it killed te enemy commander. After this I could still use manual targeting to get it to fire again but after a few buildings event that didn't work anymore and it just wouldn't fire. The only workaround I've found is to reclaim en rebuild it.
[game.log](https://github.com/FAForever/nomads/files/3995770/game.log)

**Comment by Exotic-Retard** [comment]
thanks for your report, ive put in a fix here b3461438c8b29c6abdd2e263603c5fd777675e5d
should be released next version! <3
i think ill be releasing a new patch soon since it seems to happen too often :/

**Comment by Exotic-Retard** [comment]
this has been deployed for a little bit now, should be gone. will reopen if the issue still exists.
