### ISSUE TITLE
Nomads air and naval factories build animations arent working

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/nomads#541]
This applies to t1 navy and air factories. higher techs untested but assume same issue. sounds like a regression where some code got deleted.

the build arms for the factories are supposed to move when the unit is being built, and this happens for the land factory, but not the other types, and should.

**Comment by speed2CZ** [comment]
https://github.com/FAForever/nomads/commit/8cbc6d04d4ce106d678fe7fc11ab6355fecb0ff2#diff-3ea8c231b8e883e90864421cbc00d89d 🙈

**Comment by Exotic-Retard** [comment]
xD
fixed here https://github.com/FAForever/nomads/commit/e586e92277a2d8b054be2140a78c5368344d4771
