### ISSUE TITLE
Add new death thread for T4 transport

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/nomads#547]
Its alright now, but it could be much better. The idea is to create an explosion at one of the engines, and tilt the transport to that side as it falls. Also needs an animation for moving the engines as one of them explodes but that can be provided separately

**Comment by TakesTheBiscuit** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/ljfTvNk" data-context="false" ><a href="//imgur.com/a/ljfTvNk"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by TakesTheBiscuit** [comment]
https://imgur.com/a/ljfTvNk

**Comment by TakesTheBiscuit** [comment]
Proposal for phase 1:

1. Pick an engine location: there are 8 engines, randomly select one of the engines to blow out 
2. Generate a massive explosion in that engine location on the model.
3. If left side engine and model is already on a slight left bearing, drop hard to the left
4. if model is already tilted beyond a certain scope to the right then attempt to drop the model to the left slightly but not so much that it looks 'unnatural'
5. alter the engine that blew - animating or removing it under the explosion and particle generation
