### ISSUE TITLE
t1 transport drops units from to high up, destroying them

### ISSUE THREAD

**Issue by Danthar** [FAForever/nomads#563]
Fairly often i see t1 transports drop units on from a too high altitude, causing them to crash to their deaths.

**Comment by Exotic-Retard** [comment]
could you link to a replay where that is happening? it sounds like it accidentally dropped them onto impassable terrain, water or similar, as supcom doesnt have any functionality for fall damage as such

**Comment by Danthar** [comment]
Still playing that particular game. Ill link a savegame / replay once i got it

**Comment by Danthar** [comment]
at the 59 minute. Im noticing air units not choosing the air staging which is closest by, to refuel. There are instances of it happening before. But i have a rough timestamp for this moment.

**Comment by Danthar** [comment]
Ok i have a local replay file.
https://www.dropbox.com/s/w8wa8msqwqdyoi6/LastGame.SCFAReplay?dl=0

Funny thing. I finished all objected, but it still said i lost in the end. However that particular issue is probably for the missions repo.

**Comment by Exotic-Retard** [comment]
just an update on this, i seem to have found an issue with dropping t1 Lavs from transports, however other units seem to drop fine. this is probably a regression with the animations

**Comment by Exotic-Retard** [comment]
fixed in 9a2a402e874204e9040e09de5a3cd99f39fa743a <3
