### ISSUE TITLE
Artillery boat ID doesn't match other factions

### ISSUE THREAD

**Issue by Apofenas** [FAForever/nomads#611]
New artillery boad uses (XNS)0104 ID. Aeon Shard with similiar role has (UAS)0102 and it would make more sense to use same ID, but (XNS)0102 is currently occupied by Railgun Carrier. That is done because UEF Cooper uses (XES)0102 instead of (XAS/XRS)0204 which are used by Aeon/Cybran t2 subs.

Proposal:
1) Switch Railgun Carrier (future EMP ship) to either (XNS)0204 which is used by t2 submarines for other factions (Vesper/Barrakuda) or to (XNS)0205 which is used by t2 support ships (Bullwark/Mermeid) for other factions.
2) Switch Artillery boat to (XNS)0102 like Shard

**Comment by Exotic-Retard** [comment]
fixed by steven in the above pr <3
