### ISSUE TITLE
Add enabled by enhancement tags to nomads ACU/SCU weapons

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/nomads#616]
Pretty much what it says on the tin, new code from faf means that we need to add these tags or the game thinks they are always enabled. Just a UI thing in the unit stats but still good to get it right.

each weapon that gets turned on needs an entry like: `EnabledByEnhancement = 'NaniteMissileSystem',` in its blueprint section. should be pretty straightforward to do for anyone whos interested.

**Comment by wodzu93** [comment]
Made pull request, please review. #617

**Comment by Exotic-Retard** [comment]
thanks <3
